#!/usr/bin/env bash
source ./cali-kind.env

# Create the Kind configuration based on our template (change ahead of time for customizations):
printf " \n"
printf "${BOLD_YELLOW}Destroying the cluster named /"${KIND_NAME_CLUSTER}/": ${CLEAR} \n"
unset KUBECONFIG
kind delete cluster --name ${KIND_NAME_CLUSTER}