#!/usr/bin/env bash
source ./cali-kind.env

# Color Definitions:
CLEAR='\033[0m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BOLD_RED='\033[1m\033[31m'
BOLD_GREEN='\033[1m\033[32m'
BOLD_YELLOW='\033[1m\033[33m'

# Create the Kind configuration based on our template (change ahead of time for customizations):
printf " \n"
printf "${BOLD_YELLOW}Writing \"kind-deployment.yaml\" based on the given environment variables: ${CLEAR} \n"
envsubst < ./configs-kind/kind-template.yaml | tee ./manifests/kind-deployment.yaml


# Create the Calico configuration for use with kind, based on our template:
printf " \n"
printf "${BOLD_YELLOW}Writing \"calico-deployment.yaml\" based on the given environment variables: ${CLEAR} \n"
envsubst < ./configs-calico/calico-template.yaml | tee ./manifests/calico-deployment.yaml

printf " \n"
printf "${BOLD_YELLOW}Creating kind cluster named \"${KIND_NAME_CLUSTER}\": ${CLEAR} \n"
kind create cluster --config manifests/kind-deployment.yaml

printf " \n"
printf "${BOLD_YELLOW}Applying Calico CNI configuration located in \"./manifests/calico-deployment.yaml\": ${CLEAR} \n"
export KUBECONFIG="$(kind get kubeconfig-path --name="${KIND_NAME_CLUSTER}")"

printf " \n"
printf "${BOLD_YELLOW}Configuring this terminal session to manage cluster named \"${KIND_NAME_CLUSTER}\": ${CLEAR} \n"
#export KUBECONFIG="$(kind get kubeconfig-path --name="${KIND_NAME_CLUSTER}")"
export KUBE_EDITOR="vi"

