# NOTES:
# CIDR: 10.244.0.0/16
# kind build node-image --type apt --cni calico-ipv6
---
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
name: calico-testing
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  serviceSubnet: "10.96.0.1/12"
  podSubnet: "10.244.0.0/16"
