#!/usr/bin/env bash
source ../cali-kind.env


# KUBERNETES CONTROL PLANE CHECK: kube-proxy
printf "${BOLD_YELLOW}Waiting for Kubernetes control plane artifacts to become stable: kube-proxy ${CLEAR} \n"
printf "${BOLD_YELLOW}Please wait${CLEAR}"
KUBE_PROXY_COUNT=$(kubectl get pods --ignore-not-found=true -l "k8s-app=kube-proxy" -n kube-system | sed '1d' | wc -l)
until [ "$(kubectl get pods -n kube-system --no-headers 2>/dev/null | grep "Running" | grep "kube-proxy" | grep "1/1" | wc -l)" -ge ${KUBE_PROXY_COUNT} ]; do
  printf '.'
  sleep 1
done
printf "${BOLD_GREEN} OK!${CLEAR}"
printf " \n"